# Generated by Django 4.1.7 on 2023-04-06 07:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("flashcards", "0004_alter_collection_created_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="collection",
            name="created_at",
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
