# Generated by Django 4.1.7 on 2023-04-09 12:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("flashcards", "0006_alter_flashcard_difficulty"),
    ]

    operations = [
        migrations.AddField(
            model_name="collection",
            name="type",
            field=models.CharField(
                choices=[("public", "Public"), ("private", "Private")],
                default="private",
                max_length=7,
            ),
        ),
        migrations.AlterField(
            model_name="collection",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
