# Generated by Django 4.1.7 on 2023-04-12 11:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("flashcards", "0008_collection_owner"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="collection",
            name="type",
            field=models.CharField(
                choices=[("0", "Public"), ("1", "Private")], default="1", max_length=7
            ),
        ),
    ]
