# Generated by Django 4.1.7 on 2023-04-12 12:08

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("flashcards", "0009_user_alter_collection_type"),
    ]

    operations = [
        migrations.DeleteModel(
            name="User",
        ),
    ]
