# Generated by Django 4.1.7 on 2023-04-19 07:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("flashcards", "0011_alter_collection_type_quote"),
    ]

    operations = [
        migrations.AddField(
            model_name="collection",
            name="state",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
